import { finalCutDepth, type BoxSettings } from './boxSettings';
import type { Panel, Point, Segment } from './geometry';
import { panelBounds } from './geometry';

const point = (x: number, y: number): Point => {
  return { x, y };
};

const pointsEqual = (first: Point, second: Point): boolean => {
  return first.x === second.x && first.y === second.y;
};

const formatMillimetres = (value: number): string => {
  return value.toFixed(3);
};

export const generateGcode = (panels: Panel[], settings: BoxSettings): string => {
  const lines = [
    '%',
    `(${settings.job_name} generated by box-creator)`,
    '(GRBL compatible, millimetres, absolute positioning)',
    `(stock ${formatMillimetres(settings.stock_width)} x ${formatMillimetres(settings.stock_height)} mm)`,
    'G21',
    'G90',
    'G94',
    `G0 Z${formatMillimetres(settings.safe_height)}`,
    `S${settings.spindle_speed.toFixed(0)} M3`
  ];

  for (const [stockIndex, stockPanels] of panelsByStock(panels)) {
    if (stockIndex > 0) {
      lines.push(
        'M5',
        `M0 (load stock sheet ${stockIndex + 1})`,
        `S${settings.spindle_speed.toFixed(0)} M3`
      );
    }
    lines.push(`(stock sheet ${stockIndex + 1})`);
    writePanelProfiles(lines, stockPanels.map(localPanel), settings);
  }

  lines.push('M5', `G0 Z${formatMillimetres(settings.safe_height)}`, 'M30', '%');
  return `${lines.join('\n')}\n`;
};

const panelsByStock = (panels: Panel[]): Array<[number, Panel[]]> => {
  const indexes = [...new Set(panels.map((panel) => panel.stock_index))].sort(
    (first, second) => first - second
  );
  return indexes.map((stockIndex) => [
    stockIndex,
    panels.filter((panel) => panel.stock_index === stockIndex)
  ]);
};

const localPanel = (panel: Panel): Panel => {
  const offsetX = panel.stock_origin_x;
  const offsetY = panel.stock_origin_y;
  return {
    name: panel.name,
    width: panel.width,
    height: panel.height,
    origin_x: panel.origin_x - offsetX,
    origin_y: panel.origin_y - offsetY,
    outline: panel.outline.map((outlinePoint) =>
      point(outlinePoint.x - offsetX, outlinePoint.y - offsetY)
    ),
    relief_points: panel.relief_points.map((reliefPoint) =>
      point(reliefPoint.x - offsetX, reliefPoint.y - offsetY)
    ),
    stock_index: panel.stock_index,
    stock_origin_x: 0.0,
    stock_origin_y: 0.0
  };
};

const writePanelProfiles = (lines: string[], panels: Panel[], settings: BoxSettings): void => {
  lines.push(`(profile cut with ${formatMillimetres(settings.bit_diameter)} mm cutter)`);
  for (const panel of panels) {
    lines.push(`(${panel.name} panel)`);
    let currentDepth = 0.0;
    const targetDepth = finalCutDepth(settings);
    while (currentDepth > targetDepth) {
      currentDepth = Math.max(currentDepth - settings.cut_depth_step, targetDepth);
      writeProfilePass(lines, panel, currentDepth, settings);
    }
  }
};

const writeProfilePass = (
  lines: string[],
  panel: Panel,
  depth: number,
  settings: BoxSettings
): void => {
  const originalPoints = panel.outline;
  const points = offsetClosedOutline(panel.outline, settings.bit_diameter * 0.5);
  if (points.length < 2) {
    return;
  }

  const start = points[0];
  if (start === undefined) {
    return;
  }

  lines.push(
    `G0 X${formatMillimetres(start.x)} Y${formatMillimetres(start.y)}`,
    `G0 Z${formatMillimetres(settings.surface_height)}`,
    `G1 Z${formatMillimetres(depth)} F${settings.plunge_rate.toFixed(0)}`,
    `G1 F${settings.feed_rate.toFixed(0)}`
  );

  for (let index = 0; index < points.length - 1; index += 1) {
    const offsetStart = points[index];
    const offsetEnd = points[index + 1];
    const originalStart = originalPoints[index];
    const originalEnd = originalPoints[index + 1];
    if (
      offsetStart === undefined ||
      offsetEnd === undefined ||
      originalStart === undefined ||
      originalEnd === undefined
    ) {
      continue;
    }
    if (settings.include_tabs && isBoundingEdge(panel, originalStart, originalEnd)) {
      writeSegmentWithTabs(lines, offsetStart, offsetEnd, depth, settings);
    } else {
      lines.push(`G1 X${formatMillimetres(offsetEnd.x)} Y${formatMillimetres(offsetEnd.y)}`);
    }
  }

  lines.push(`G0 Z${formatMillimetres(settings.safe_height)}`);
};

const offsetClosedOutline = (points: Point[], distance: number): Point[] => {
  if (points.length < 3 || distance <= 0.0) {
    return points;
  }

  const firstPoint = points[0];
  const lastPoint = points[points.length - 1];
  const outline =
    firstPoint !== undefined && lastPoint !== undefined && pointsEqual(lastPoint, firstPoint)
      ? points.slice(0, -1)
      : points;

  if (outline.length < 3) {
    return points;
  }

  const area = signedArea(outline);
  if (Math.abs(area) < 0.001) {
    return points;
  }

  const offsetDistance = area > 0.0 ? distance : -distance;
  const offsetPoints: Point[] = [];
  for (const [index, outlinePoint] of outline.entries()) {
    const previousPoint = outline[index - 1] ?? outline[outline.length - 1];
    const nextPoint = outline[(index + 1) % outline.length];
    if (previousPoint === undefined || nextPoint === undefined) {
      continue;
    }

    const previousLine = offsetLine(previousPoint, outlinePoint, offsetDistance);
    const nextLine = offsetLine(outlinePoint, nextPoint, offsetDistance);
    offsetPoints.push(
      lineIntersection(previousLine, nextLine) ??
        offsetPoint(outlinePoint, previousPoint, nextPoint, offsetDistance)
    );
  }

  const firstOffsetPoint = offsetPoints[0];
  if (firstOffsetPoint !== undefined) {
    offsetPoints.push(firstOffsetPoint);
  }
  return offsetPoints;
};

const offsetLine = (start: Point, end: Point, distance: number): Segment => {
  const dx = end.x - start.x;
  const dy = end.y - start.y;
  const length = Math.sqrt(dx * dx + dy * dy);
  if (length <= 0.0001) {
    return { start, end };
  }
  const normalX = dy / length;
  const normalY = -dx / length;
  return {
    start: point(start.x + normalX * distance, start.y + normalY * distance),
    end: point(end.x + normalX * distance, end.y + normalY * distance)
  };
};

const lineIntersection = (first: Segment, second: Segment): Point | undefined => {
  const firstDx = first.end.x - first.start.x;
  const firstDy = first.end.y - first.start.y;
  const secondDx = second.end.x - second.start.x;
  const secondDy = second.end.y - second.start.y;
  const denominator = firstDx * secondDy - firstDy * secondDx;
  if (Math.abs(denominator) <= 0.0001) {
    return undefined;
  }
  const offsetX = second.start.x - first.start.x;
  const offsetY = second.start.y - first.start.y;
  const distanceOnFirst = (offsetX * secondDy - offsetY * secondDx) / denominator;
  return point(
    first.start.x + firstDx * distanceOnFirst,
    first.start.y + firstDy * distanceOnFirst
  );
};

const offsetPoint = (
  outlinePoint: Point,
  previousPoint: Point,
  nextPoint: Point,
  distance: number
): Point => {
  const previousDx = outlinePoint.x - previousPoint.x;
  const previousDy = outlinePoint.y - previousPoint.y;
  const nextDx = nextPoint.x - outlinePoint.x;
  const nextDy = nextPoint.y - outlinePoint.y;
  const previousLength = Math.sqrt(previousDx * previousDx + previousDy * previousDy);
  const nextLength = Math.sqrt(nextDx * nextDx + nextDy * nextDy);
  if (previousLength <= 0.0001 || nextLength <= 0.0001) {
    return outlinePoint;
  }
  const normalX = previousDy / previousLength + nextDy / nextLength;
  const normalY = -previousDx / previousLength + -nextDx / nextLength;
  const normalLength = Math.sqrt(normalX * normalX + normalY * normalY);
  if (normalLength <= 0.0001) {
    return outlinePoint;
  }
  return point(
    outlinePoint.x + (normalX / normalLength) * distance,
    outlinePoint.y + (normalY / normalLength) * distance
  );
};

const writeSegmentWithTabs = (
  lines: string[],
  start: Point,
  end: Point,
  depth: number,
  settings: BoxSettings
): void => {
  const dx = end.x - start.x;
  const dy = end.y - start.y;
  const length = Math.sqrt(dx * dx + dy * dy);
  if (length < settings.tab_width * 2.0) {
    lines.push(`G1 X${formatMillimetres(end.x)} Y${formatMillimetres(end.y)}`);
    return;
  }

  const tabCount = tabCountForSegment(length, settings.tab_width);
  const ranges: Array<[number, number]> = [];
  for (let index = 0; index < tabCount; index += 1) {
    const center = (length * (index + 1)) / (tabCount + 1);
    ranges.push([center - settings.tab_width * 0.5, center + settings.tab_width * 0.5]);
  }

  let current = 0.0;
  for (const [tabStart, tabEnd] of ranges) {
    moveAlongSegment(lines, start, dx, dy, length, tabStart);
    if (depth < -settings.tab_height) {
      lines.push(
        `G1 Z${formatMillimetres(-settings.tab_height)} F${settings.plunge_rate.toFixed(0)}`
      );
    }
    moveAlongSegment(lines, start, dx, dy, length, tabEnd);
    if (depth < -settings.tab_height) {
      lines.push(`G1 Z${formatMillimetres(depth)} F${settings.plunge_rate.toFixed(0)}`);
    }
    current = tabEnd;
  }

  if (current < length) {
    lines.push(`G1 X${formatMillimetres(end.x)} Y${formatMillimetres(end.y)}`);
  }
};

const moveAlongSegment = (
  lines: string[],
  start: Point,
  dx: number,
  dy: number,
  length: number,
  distance: number
): void => {
  const clamped = Math.max(0.0, Math.min(length, distance));
  const ratio = clamped / length;
  const xPosition = start.x + dx * ratio;
  const yPosition = start.y + dy * ratio;
  lines.push(`G1 X${formatMillimetres(xPosition)} Y${formatMillimetres(yPosition)}`);
};

export const tabCountForSegment = (length: number, tabWidth: number): number => {
  if (length < tabWidth * 4.0) {
    return 1;
  }
  return 2;
};

export const isBoundingEdge = (panel: Panel, start: Point, end: Point): boolean => {
  const bounds = panelBounds(panel);
  const tolerance = 0.001;
  return (
    (Math.abs(start.x - end.x) < tolerance &&
      (Math.abs(start.x - bounds.min_x) < tolerance ||
        Math.abs(start.x - bounds.max_x) < tolerance)) ||
    (Math.abs(start.y - end.y) < tolerance &&
      (Math.abs(start.y - bounds.min_y) < tolerance ||
        Math.abs(start.y - bounds.max_y) < tolerance))
  );
};

const signedArea = (outline: Point[]): number => {
  let area = 0.0;
  for (const [index, start] of outline.entries()) {
    const end = outline[(index + 1) % outline.length];
    if (end !== undefined) {
      area += start.x * end.y - end.x * start.y;
    }
  }
  return area * 0.5;
};
